### ISSUE TITLE
Custom Providers only use the first 4 characters from config name

### ISSUE THREAD

**Issue by niki-on-github** [jamesmcm/vopono#115]
The current version use for an [custom-provider](https://github.com/jamesmcm/vopono/blob/master/USERGUIDE.md#custom-providers) only the [first 4 characters](https://github.com/jamesmcm/vopono/blob/0.8.8/src/exec.rs#L136) of the config file name.  If the filenames all have the same prefix this will cause problems if you want to run multiple vpn connections with custom provider.

Is there a reason why it is limited to 4 symbols? If so, it would be helpful if this is mentioned in a sentence in the [userguide](https://github.com/jamesmcm/vopono/blob/master/USERGUIDE.md#custom-providers) in the custom providers section.

**Comment by jamesmcm** [comment]
The issue is that it's used for the device name and that can only be 16 chars total - https://stackoverflow.com/questions/24932172/what-length-can-a-network-interface-name-have

One approach would be to hash the names, which I think is left as TODO in the comment there.

I think a combination of that and renaming the prefix from "vopono_" to just "vp_" would help.

I'll take a look if I get some time. If you're using a public VPN provider though, it would also be good to contribute a config set up to `vopono sync`.

**Comment by niki-on-github** [comment]
>> If you're using a public VPN provider though, it would also be good to contribute a config set up to vopono sync.

I have tried to add my [provider airvpn](https://github.com/niki-on-github/vopono/tree/feature/airvpn). But currently authentication without auth file is not implemented for your [`verify_auth`](https://github.com/jamesmcm/vopono/blob/0.8.8/src/exec.rs#L273) function (except for custom providers).

**Comment by jamesmcm** [comment]
vopono creates the auth file though, but yeah it'd good to make it optional in case you don't want to save the credentials.

**Comment by jamesmcm** [comment]
If it's included in the config file, the easiest way would be to extract it in to auth.txt in the sync script and modify the config file.

e.g. in Mullvad OpenVPN we write the OpenVPN config file directly - https://github.com/jamesmcm/vopono/blob/master/src/providers/mullvad/openvpn.rs

**Comment by niki-on-github** [comment]
AirVPN uses private keys inside ovpn for auth. The problem is when we pass an empty auth file openvpn does not start:

```
1639311886.361096 40 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
1639311886.361181 40 WARNING: file '/home/arch/.config/vopono/AirVPN/openvpn/unused.txt' is group or others accessible
1639311886.361191 1 OpenVPN 2.5.4 [git:makepkg/3f7a85b9aebe7be0+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct  5 2021
1639311886.361198 1 library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10
1639311886.361216 10 ERROR: username from Auth authfile '/home/arch/.config/vopono/AirVPN/openvpn/unused.txt' is empty
1639311886.361221 1 Exiting due to fatal error
```

**Comment by niki-on-github** [comment]
Writing some random string into the file seems to solve the problem.

**Comment by jamesmcm** [comment]
Yeah, we'll need to modify the VPN Provider API slightly so the authfile path is  optional e.g. returns `Result<Option<PathBuf>>`

https://github.com/jamesmcm/vopono/blob/master/src/providers/mod.rs#L127

And the check in exec.rs needs to be aware of it:
https://github.com/jamesmcm/vopono/blob/master/src/exec.rs#L272-L276
  (i.e. use `.map(|x| verify_auth(x))` )

**Comment by jamesmcm** [comment]
The change to use a hash for the veth link name and network namespace name for custom provider config files is done in vopono 0.8.9 so please try that.

I'll take a look at merging your changes to make the auth optional and add support for AirVPN config generation soon :slightly_smiling_face:

**Comment by niki-on-github** [comment]
Thanks looks good!

I have submitted my changes for the provider AirVPN as a pull request #121.
