### ISSUE TITLE
Version 0.8.8 not available in crates.io

### ISSUE THREAD

**Issue by romildo** [jamesmcm/vopono#118]
The NixOS package for vopono downloads the source from crates.io. The latest release (v0.8.8) is not available there yet.
Not being a rust developer (yet) I do not know exactly how this works. Each new release is normally made available there?

**Comment by jamesmcm** [comment]
This should be uploaded now.

Could you share the package script btw?

**Comment by romildo** [comment]
Thanks.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/vopono/default.nix

**Comment by romildo** [comment]
[NixOS](https://nixos.org) uses its own language (called Nix) for packaging.
