### ISSUE TITLE
nmcli general reload doesn't exist

### ISSUE THREAD

**Issue by 01bd881d** [jamesmcm/vopono#12]
`sudo vopono -v exec --custom ./us-free-03.protonvpn.com.udp.ovpn --protocol openvpn "brave-browser"
[sudo] password for user: 
 2020-08-08T22:05:03.524Z DEBUG vopono::util > Existing namespaces: []
 2020-08-08T22:05:03.561Z DEBUG vopono::network_interface > ip addr
 2020-08-08T22:05:03.677Z DEBUG vopono                    > Interface: eth0
 2020-08-08T22:05:03.693Z DEBUG vopono::util              > Existing namespaces: []
 2020-08-08T22:05:03.693Z DEBUG vopono::util              > ip netns add vopono_cus_usfr
 2020-08-08T22:05:03.736Z DEBUG vopono::util              > Existing interfaces: 
 2020-08-08T22:05:04.026Z DEBUG vopono::util              > Assigned IPs: []
 2020-08-08T22:05:04.054Z DEBUG vopono::netns             > ip netns exec vopono_cus_usfr ip addr add 127.0.0.1/8 dev lo
 2020-08-08T22:05:04.145Z DEBUG vopono::netns             > ip netns exec vopono_cus_usfr ip link set lo up
 2020-08-08T22:05:04.249Z DEBUG vopono::veth_pair         > NetworkManager detected, adding cus_usfr_d to unmanaged devices
 2020-08-08T22:05:04.274Z DEBUG vopono::util              > nmcli general reload
Error: argument 'reload' not understood. Try passing --help instead.
 2020-08-08T22:05:04.729Z DEBUG vopono::util              > ip netns delete vopono_cus_usfr
Error: Failed to reload NetworkManager configuration

Caused by:
    Command failed: nmcli general reload`

Looking throw [this](https://developer.gnome.org/NetworkManager/stable/nmcli.html) documentation the correct command would be:
`nmcli connection reload`

I'm using debian and the .deb package provided on the realease page

**Comment by jamesmcm** [comment]
Hi,

Are you using NetworkManager? If so then you should have `nmcli` installed. If not then delete the `/etc/NetworkManager` directory.

I'll fix this so that it verifies NetworkManager is actually active and installed in any case.

**Comment by jamesmcm** [comment]
I'll also try to add proper ProtonVPN support soon like the other providers.

Are you using the Basic or Plus account btw? It seems the latter has extra servers?

**Comment by jamesmcm** [comment]
Actually I realised I misread the original issue, sorry.

What version of `nmcli` are you using?

i.e.
```
$ nmcli --version
nmcli tool, version 1.26.0-1
```

It seems the command is version dependent, as `nmcli general reload` works for me.

**Comment by jamesmcm** [comment]
Okay, please try the new v0.3.1 release: https://github.com/jamesmcm/vopono/releases/tag/0.3.1 :slightly_smiling_face:

**Comment by 01bd881d** [comment]
Okey, I try version 0.3.1 and a similar error appear:

> sudo vopono -v exec --custom ./us-free-03.protonvpn.com.udp.ovpn --protocol openvpn "brave-browser"
>  2020-08-09T14:43:59.887Z DEBUG vopono::util > Existing namespaces: []
>  2020-08-09T14:43:59.887Z DEBUG vopono::network_interface > ip addr
>  2020-08-09T14:43:59.890Z DEBUG vopono                    > Interface: wlan0
>  2020-08-09T14:43:59.892Z DEBUG vopono::util              > Existing namespaces: []
>  2020-08-09T14:43:59.892Z DEBUG vopono::util              > ip netns add vopono_custom_usfr
>  2020-08-09T14:43:59.897Z DEBUG vopono::util              > Existing interfaces: 
>  2020-08-09T14:43:59.899Z DEBUG vopono::util              > Assigned IPs: []
>  2020-08-09T14:43:59.899Z DEBUG vopono::netns             > ip netns exec vopono_custom_usfr ip addr add 127.0.0.1/8 dev lo
>  2020-08-09T14:43:59.969Z DEBUG vopono::netns             > ip netns exec vopono_custom_usfr ip link set lo up
>  2020-08-09T14:44:00.029Z DEBUG vopono::veth_pair         > NetworkManager detected, adding custom_usfr_d to unmanaged devices
>  2020-08-09T14:44:00.029Z DEBUG vopono::util              > nmcli connection reload
>  2020-08-09T14:44:00.171Z DEBUG vopono::util              > ip link add custom_usfr_d type veth peer name custom_usfr_s
>  2020-08-09T14:44:00.206Z DEBUG vopono::util              > ip link set custom_usfr_d up
>  2020-08-09T14:44:00.209Z DEBUG vopono::util              > ip link set custom_usfr_s netns vopono_custom_usfr up
>  2020-08-09T14:44:00.241Z DEBUG vopono::util              > ip addr add 10.200.1.1/24 dev custom_usfr_d
>  2020-08-09T14:44:00.251Z DEBUG vopono::netns             > ip netns exec vopono_custom_usfr ip addr add 10.200.1.2/24 dev custom_usfr_s
>  2020-08-09T14:44:00.321Z DEBUG vopono::netns             > ip netns exec vopono_custom_usfr ip route add default via 10.200.1.1 dev custom_usfr_s
>  2020-08-09T14:44:00.369Z DEBUG vopono::util              > iptables -t nat -A POSTROUTING -s 10.200.1.0/24 -o wlan0 -j MASQUERADE
>  2020-08-09T14:44:00.473Z DEBUG vopono::util              > sysctl -q net.ipv4.ip_forward=1
>  2020-08-09T14:44:00.497Z DEBUG vopono::dns_config        > Setting namespace vopono_custom_usfr DNS server to 8.8.8.8
>  2020-08-09T14:44:00.498Z DEBUG vopono::util              > ip link delete custom_usfr_d
>  2020-08-09T14:44:00.554Z DEBUG vopono::util              > nmcli general reload
> Error: argument 'reload' not understood. Try passing --help instead.
> thread 'main' panicked at 'Failed to reload NetworkManager configuration: Command failed: nmcli general reload', src/veth_pair.rs:127:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>  2020-08-09T14:44:00.572Z DEBUG vopono::util              > iptables -t nat -D POSTROUTING -s 10.200.1.0/24 -o wlan0 -j MASQUERADE


I take a look at the code and on line 126 on veth_pair.rs you have the command:
`sudo_command(&["nmcli", "general", "reload"])`

I'm using MX Linux (Debian 10 buster) and a free plan of protonVPN.
`nmcli tool, version 1.14.6`

I think would be nice to merge this project to the [ProtonVPN-Gui-Linux app](https://github.com/ProtonVPN/linux-gui) to have a similar experience like Windows ProtonVPN app tunneling certain apps.

**Comment by jamesmcm** [comment]
Thanks, I updated it in the new release (v0.3.1 - see commit https://github.com/jamesmcm/vopono/commit/3c4709dc21fe4937b4b803083b9d8b752bd3a716 ) so please try that.


> I think would be nice to merge this project to the ProtonVPN-Gui-Linux app to have a similar experience like Windows ProtonVPN app tunneling certain apps.

I'll try that out when I create a ProtonVPN account so I can see how much work it would be.

I usually use Mullvad.
