### ISSUE TITLE
Latest version not available in crates.io

### ISSUE THREAD

**Issue by romildo** [jamesmcm/vopono#161]
The [NixOS package for vopono](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/vopono/default.nix) downloads the source from [crates.io](https://crates.io/crates/vopono/versions). The latest release (0.9.1) is not available there yet.

Could it be kept up to date?

**Comment by jamesmcm** [comment]
Thanks for letting me know, it should be updated now.
