### ISSUE TITLE
What are those DNS rules in the firewall for?

### ISSUE THREAD

**Issue by ak-1** [jamesmcm/vopono#162]
vopono adds rules to the firewall allowing direct connection to the DNS servers. But if I remove those rules everything still seems to work fine. What is the purpose of those rules?

**Comment by jamesmcm** [comment]
Are you using OpenVPN or Wireguard? I think they are necessary in the Wireguard case IIRC.

**Comment by ak-1** [comment]
I am using OpenVPN. Would it be a good idea then to only add those rules for Wireguard? Maybe those rules could also be limited on port/protocol?

**Comment by jamesmcm** [comment]
Closing since addressed in #167
