### ISSUE TITLE
Running second instance of browser with Vopono

### ISSUE THREAD

**Issue by ghost** [jamesmcm/vopono#164]
Not sure if this is actual issue or I'm doing something wrong. I run chromium with command line:

`vopono exec --provider ProtonVPN --server netherlands "chromium --profile-directory=Profile2"`

But it says:

` chromium is already running. You must force it to use a separate profile in order to launch a new process!`

It actually starts with Profile2, but VPN has no effect on it. I know I can just run another browser like chromium beta or google-chrome, but it is possible to run multiple instances of same application?

**Comment by dchusovitin** [comment]
It's because chromium reuses the same master process.
In order to run a completely different instance of chromium instance, you need to run:

```
chromuim --user-data-dir=/tmp/profile-2
```

```
Separate instances of Chromium must use separate user data directories; repeated invo‐      
              cations of chromium will reuse an existing process for a given user data directory.     
```
