### ISSUE TITLE
rustc + cargo 2021 in debian stable on armv5

### ISSUE THREAD

**Issue by VR-Punk** [jamesmcm/vopono#166]
hi,

debian stable provides rustc 1.48.0 and cargo 1.46.0 and if run your install.sh form the vopono 0.9.1.tar.gz i got this error:

"this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions"

if i want to build the newest version of rust and cargo from source i got the error: 

unknown cpu type: armv5tel

Can I "downgrade" the setting in your Cargo.toml of the vopono 0.9.1.tar.gz from edition 2021 to 2018 without causing problems ?

**Comment by jamesmcm** [comment]
You can try it, but I think it might be an issue for some of the dependencies.

**Comment by VR-Punk** [comment]
The latest version of vopono, which is using "rust/cargo edition = "2018" seems to be  vopono v0.8.11 ?

But the dependencies are using "rust/cargo edition = "2021" ?

Installing vopono v0.8.11
Updating crates.io index
error: failed to compile `vopono v0.8.11 intermediate artifacts can be found at `/vopono-0.8.11/target`

Caused by:
failed to download `hashbrown v0.12.1`

Caused by:
unable to get packages from source

Caused by:
 failed to parse manifest at /.cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.1/Cargo.toml`

Caused by:
failed to parse the `edition` key

Caused by:
this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

**Comment by VR-Punk** [comment]
Is there any way to use vopono on a debian, which doesn't support the newer versions of rustc and cargo ? For example docker or something like that ?

**Comment by jamesmcm** [comment]
It should be possible to cross-compile without docker, but you could also try adapting this: https://hub.docker.com/layers/blemelin/rust-armv5-musl/latest/images/sha256-0ec1abe798cb95a5a03bbcf5b167d302fe7e4c5bf8d63e5fc057bcefcf3fc2e2?context=explore

**Comment by jamesmcm** [comment]
Sure, the main security related changes are usually to firewall rules and I don't think there's been any changes there recently.

I can also take a look at adding arm5 to the built binaries in Github actions (adapting the Dockerfile above).

**Comment by VR-Punk** [comment]
arm5 binaries would be a great relief ! I'm not good in compiling and i have never cross compiled something !

**Comment by jamesmcm** [comment]
They're now available in the latest release, hopefully they work on your device, I don't have anything to test on unfortunately.

**Comment by VR-Punk** [comment]
Thank you very much !!! I did a short test tonight, and it works ! I will test it more accurate this week, and i will tell you the success (hopefully) ! Thx! Thx! Thx!

**Comment by VR-Punk** [comment]
It works great ! I have tested it more accurate and it is my daily driver, now !

**Comment by jamesmcm** [comment]
Perfect, I'll try to add #169 for the next release too to cover all Arch Linux ARM supported platforms too.
