### ISSUE TITLE
Add Mullvad Port Forwarding option to vopono sync

### ISSUE THREAD

**Issue by jamesmcm** [jamesmcm/vopono#184]
Atm you have to enable it manually on the dashboard after Wireguard keypair generation - https://mullvad.net/en/account/#/ports

Check if this can be done with the API too

**Comment by hashworks** [comment]
Looks like there are open issues for the official apps regarding this feature: https://github.com/mullvad/mullvadvpn-app/issues/2938#issuecomment-912533067

On [Sep 3, 2021](https://github.com/mullvad/mullvadvpn-app/issues/2938#issuecomment-912533067) they said:
> We don't currently have any public API where you can manage your port forwarding. So no luck sadly.

**Comment by jamesmcm** [comment]
Damn, that's a shame, hopefully it'll be possible in the future, I'll close it for now though.

Thanks for the info!
