### ISSUE TITLE
buy recommendation

### ISSUE THREAD

**Issue by VR-Punk** [jamesmcm/vopono#199]
I'm going to buy a new NAS and i may ask you which one is supported by vopono  ? 

(A the moment vopono runs mullvad on a older Linkstation (LS-QVL) with Debian  Bullseye.)

**Comment by jamesmcm** [comment]
Any NAS which supports the modern mainline Linux kernel (i.e. Linux 5.6+ for full Wireguard and nftables support) should be fine.

For a pre-built solution it seems people recommend Synology for Linux - https://linuxhint.com/nas_server_home/

Even the Celeron processors are 64-bit so I don't think there should be any issues.

**Comment by VR-Punk** [comment]
https://www.amazon.com/Synology-Bay-DiskStation-DS220-Diskless/dp/B087ZCBWFH

Celeron 1007U
Kernel 4.4.180  
Docker Compose 1.28.5

or

https://www.amazon.de/Qnap-TS-462-2G-Desktop-NAS-Enclosure/dp/B0BJVX934S/

Celeron N4505 
Kernel 5.10.60
Container Station (VM, LXD, Docker, Kata)

**Comment by VR-Punk** [comment]
Synology announced Kernel 5.10 in next update in 2 or 3 month

**Comment by VR-Punk** [comment]
Can i build a docker file of vopono, if Synology will release their updates with new kernel versions a few month too late ?

**Comment by jamesmcm** [comment]
Between the two the Qnap looks better, but is more expensive.

If you're using docker, I wouldn't use vopono but instead just make the container route through the VPN directly e.g. via gluetun or in the Dockerfile directly.

See:
https://www.pedrolamas.com/2020/11/20/how-to-connect-to-a-wireguard-vpn-server-from-a-docker-container/ - using Wireguard in the Docker container directly
https://medium.com/linux-shots/put-a-docker-container-behind-vpn-fdc0e32c9ca5 - making the container connect via the VPN using gluetun

**Comment by VR-Punk** [comment]
The Qnap seems to have faster updates, with newer software.

Can you give me a list of all dependencies of vopono ? I want to ask in a Qnap and Synology forum if i can build the missing packages, on their heavily customized linux os .

**Comment by VR-Punk** [comment]
I will buy a qnap, because if i can't build vopono i will install debian in a VM (Qemu). The Qnap OS officially supports (Qemu) VM's. But i still prefer to build vopono !

Thanks for your advice !
