### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by darrena** [jamesmcm/vopono#2]
I saw your post on Reddit and decided to try it out. I downloaded the latest from Git and ran install.sh and received the following error:
--------------------------------------------------------------------------------------------------------------

 Installing vopono v0.1.2 (/home/darren/bin/vopono)
    Updating crates.io index
   Compiling compound_duration v1.2.0
   Compiling libc v0.2.71
   Compiling proc-macro2 v1.0.18
   Compiling syn v1.0.33
   Compiling serde_derive v1.0.114
   Compiling getrandom v0.1.14
   Compiling bitflags v1.2.1
   Compiling serde v1.0.114
   Compiling proc-macro-error-attr v1.0.3
   Compiling byteorder v1.3.4
   Compiling num-traits v0.2.12
   Compiling proc-macro-error v1.0.3
   Compiling num-integer v0.1.43
   Compiling heck v0.3.1
   Compiling ryu v1.0.5
   Compiling memchr v2.3.3
   Compiling anyhow v1.0.31
   Compiling nix v0.17.0
   Compiling walkdir v2.3.1
   Compiling log v0.4.8
error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
  --> /home/darren/.cargo/registry/src/github.com-1ecc6299db9ec823/compound_duration-1.2.0/src/lib.rs:40:27
   |
40 |         (seconds & usize::MAX.try_into().unwrap())
   |                           ^^^ associated item not found in `usize`
   |
help: you are looking for the module in `std`, not the primitive type
   |
40 |         (seconds & std::usize::MAX.try_into().unwrap())
   |                    ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
  --> /home/darren/.cargo/registry/src/github.com-1ecc6299db9ec823/compound_duration-1.2.0/src/lib.rs:96:27
   |
96 |         (seconds & usize::MAX.try_into().unwrap())
   |                           ^^^ associated item not found in `usize`
   |
help: you are looking for the module in `std`, not the primitive type
   |
96 |         (seconds & std::usize::MAX.try_into().unwrap())
   |                    ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
   --> /home/darren/.cargo/registry/src/github.com-1ecc6299db9ec823/compound_duration-1.2.0/src/lib.rs:161:25
    |
161 |         (nanos & usize::MAX.try_into().unwrap()).try_into().unwrap()
    |                         ^^^ associated item not found in `usize`
    |
help: you are looking for the module in `std`, not the primitive type
    |
161 |         (nanos & std::usize::MAX.try_into().unwrap()).try_into().unwrap()
    |                  ^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `compound_duration`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `vopono v0.1.2 (/home/darren/bin/vopono)`, intermediate artifacts can be found at `/home/darren/bin/vopono/target`

Caused by:
  build failed
----------------------------------------------------------------------------------------

I haven't used Rust before but am I reading this right that it is grabbing dependencies and building them so this is probably an issue upstream from you with the dependency compound_duration?

Please let me know if there are more logs I can provide or if Ubuntu is just not supported at this time.

Thanks!

**Comment by jamesmcm** [comment]
Hi,

Could you please post your rust version?

```bash
$ rustc -V
```

It seems that dependency has issues with rustc below 1.43.

**Comment by jamesmcm** [comment]
Overall I'd recommend using rustup to install Rust: https://rustup.rs/ to avoid issues with the repos like this.

**Comment by darrena** [comment]
> Hi,
> 
> Could you please post your rust version?
> 
> ```shell
> $ rustc -V
> ```
> 
> It seems that dependency has issues with rustc below 1.43.

It looks like I have 1.41.0 so that is the issue.  I will try rustup.rs later today and will close this bug report.  Thanks!
