### ISSUE TITLE
Clean up Box::leak() calls for skipping destructors

### ISSUE THREAD

**Issue by jamesmcm** [jamesmcm/vopono#20]
vopono uses the [Drop trait](https://doc.rust-lang.org/std/ops/trait.Drop.html) to automatically clean up resources when the relevant structs go out of scope. However, sometimes we don't want to trigger these destructors but still have the structs go out of scope - for example, if we have multiple vopono processes running applications in the same network namespace, then we don't want to destroy the network namespace until the final application has terminated. So if lockfiles still exist, we need to prevent the clean-up destructors from firing for the vopono instances terminated first.

For now this is done by putting the relevant structs in a Box, and then calling `Box::leak()` ([docs here](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak)). This works but feels a bit clunky when dealing with multiple structs/fields (e.g. [here preventing the destructors when another vopono instance is using the same namespace](https://github.com/jamesmcm/vopono/blob/4ebf4b6bdc493c4d95bf6e237136b330723aaf27/src/netns.rs#L308)).

One possible alternative might be to use [std::mem::ManuallyDrop](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html), however then the `drop()` method is unsafe, so this might end up being even less ergonomic.

Note that for the `vopono list` and cleaning dead namespaces cases we could at least deserialize to a read-only version of the LockFile struct:
https://github.com/jamesmcm/vopono/blob/014cd42e364545f500c03499b3df60292ffa3c33/src/util/mod.rs#L240-L242
https://github.com/jamesmcm/vopono/blob/b75442023c8f9494caa0cc709ca61c7c8e226f1f/src/list.rs#L45-L47

But for the usual Drop in netns.rs we would need a real solution:
https://github.com/jamesmcm/vopono/blob/4ebf4b6bdc493c4d95bf6e237136b330723aaf27/src/netns.rs#L305-L324

**Comment by SilensAngelusNex** [comment]
Have you looked into using [`std::mem::forget`](https://doc.rust-lang.org/std/mem/fn.forget.html)?

`Box::leak` will not only stop the boxed value from being dropped, but also leaks the heap memory the `Box` allocated. `forget` just prevents the forgotten value's `drop` from running; the (stack) memory that stored it will still be reclaimed.

You could also wrap the value in a [`ManuallyDrop`](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html) with `ManuallyDrop::new`, then neglect to call `ManuallyDrop::drop`, but that's essentially equivalent to calling `forget`, except less explicit.

**Comment by jamesmcm** [comment]
Thanks, I'll try this since we don't use the Boxes for anything :slightly_smiling_face:

**Comment by jamesmcm** [comment]
Fixed in #42
