### ISSUE TITLE
ProtonVPN Plus D'ont work

### ISSUE THREAD

**Issue by grcear** [jamesmcm/vopono#201]
Hello,

I have the problem when I want to use vopono sync to be able to deposit my Proton account I get after the selection ->ProtonVPN->Plus->Standart->P2P->tcp the error message: "Error: invalid Zip archive: Could not find central directory end". 
If I ->ProtonVPN->Free->TCP I get further in the menu

What am I doing wrong?

**Comment by jamesmcm** [comment]
It sounds like they moved the config files location, I'll take a look.

**Comment by SnuktheGreat** [comment]
I ran into this too just now. It looks like the Plus tier requires you to sign in now. The url with Tier=2 results in status code 422 with body `{"Code":2026,"Error":"User does not have access to requested server","Details":{}}`, while Tier=0 works as normal.

**Comment by rknegjens** [comment]
So is the conclusion that the plus tier will no longer work with vopono?

**Comment by jamesmcm** [comment]
It should be possible to use the session cookie in the request in `vopono sync`.

The user would have to provide it though.

**Comment by octaskin** [comment]
> use the session cookie in the request in vopono sync

@jamesmcm can you elaborate on this?

**Comment by jamesmcm** [comment]
To emulate how you download it via the browser normally, with the session cookie set it should be possible to access stuff behind the authentication check.

Similar to how `cargo-aoc` does it for Advent Of Code.

**Comment by octaskin** [comment]
Thanks for the explanation, although I was asking if this was possible already.
Re-reading your comment, I guess
>It should be possible

implies otherwise.

**Comment by jamesmcm** [comment]
Fixed in 0.10.6 release - https://github.com/jamesmcm/vopono/releases/tag/0.10.6

Note it is necessary to provide the `AUTH-` cookie after logging in via a browser.
