### ISSUE TITLE
Nordvpn stopped working since I have updated softwares 

### ISSUE THREAD

**Issue by rmatif** [jamesmcm/vopono#202]
Hello, 
Since I've made recent update on some of my software, I got a crash with the following error 

```
thread 'main' panicked at 'No lockfile', vopono_core/src/network/netns.rs:61:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It was working like a charm last week, How can I solve this crash ? 
Thank you

**Comment by jamesmcm** [comment]
Did you restart the computer after updating the kernel?

**Comment by defaultxr** [comment]
I'm getting a similar error:

```
 2024-02-09T09:31:39.876Z INFO  vopono_core::util > Calling sudo for elevated privileges, current user will be used as default user
 2024-02-09T09:31:41.147Z INFO  vopono::exec > Using existing namespace: vo_c_DjykLaJ, will not modify firewall rules
thread 'main' panicked at vopono_core/src/network/netns.rs:64:14:
No lockfile
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I didn't update any software. What I did:

1. Started a program with vopono. It launched fine.
2. The program (or perhaps vopono?) crashed.
3. I attempted to re-open the program through vopono, using the same command as before. Then I got this error.

Is there something I should do to clear out leftovers from a previous vopono instantiation? I tried running `sudo ip link delete vo_c_DjykLaJ_d` and running vopono again, but get the same error.

**Comment by jamesmcm** [comment]
Can you try:

```bash
$ sudo ip netns delete vo_c_DjykLaJ
$ sudo rm -r ~/.config/vopono/locks/
```

It's weird, it's like the lockfile was removed, but the network namespace wasn't.

**Comment by defaultxr** [comment]
@jamesmcm Awesome, that worked! Thank you :)
