### ISSUE TITLE
Syntax for forwarding/opening multiple ports?

### ISSUE THREAD

**Issue by SocietasCooperationis** [jamesmcm/vopono#209]
Passing -o/-f [Port_Num] seems to work but how do I specify multiple ports?

**Comment by SocietasCooperationis** [comment]
The documentation says that -f/-o can be used to specify a list of ports but I've yet to found a way to do more than one

**Comment by jamesmcm** [comment]
```
$ vopono -v exec firefox-developer-edition -o 56054 -o 1337
```

Works for me in the rules generation at least - note if forwarding ports you will need support on the VPN provider side too.
