### ISSUE TITLE
MozillaVPN - missing field `login_url`

### ISSUE THREAD

**Issue by edent** [jamesmcm/vopono#210]
Running `vopono sync` and selecting MozillaVPN gives this error:

```
INFO  vopono::sync > Starting Wireguard configuration...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { 
   kind: Decode, source: Error("missing field `login_url`", line: 1, column: 67)
 }', vopono_core/src/config/providers/mozilla/mod.rs:76:14
```

I'm running vopono 0.10.5 on Ubuntu 20.04. I have Wireguard and other relevant dependencies installed. It's a headless Linux server, if that makes a difference?

**Comment by jamesmcm** [comment]
It seems they changed the authentication flow - https://github.com/NilsIrl/MozWire/commit/43da20d1e6b6f030805b8897ebcf8a2f17e1a7c2

And deprecated the old one at some point.

I'll try to take a look some time but I don't have an account at the moment.

**Comment by edent** [comment]
Understood. If I download the config using MozWire, can I still use Vopono for namespacing?

**Comment by jamesmcm** [comment]
Yeah, if you can get the Wireguard wg-quick config file it should work.

**Comment by edent** [comment]
Cheers. Where should I put them so Vopono can see them? Sorry if that's a simple question.

**Comment by jamesmcm** [comment]
Usually in `~/.config/vopono/mozilla/wireguard/` e.g. `usa-nyc1.conf`

They should be in TOML format like:

```
[Interface]
PrivateKey = WE9URkRyZkhXbHU5TXhoRm1MRVZJ
Address = 2.2.2.2/32
DNS = 8.8.8.8

[Peer]
PublicKey = YmFzZTY0c3RyaW5nYQ==
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = 1.1.1.1:51820
```

But you can also pass the path to the file directly as a custom config too, both should work.

**Comment by edent** [comment]
Worked perfectly! Thanks :-)

`opono exec --custom ~/.config/vopono/mozilla/wireguard/fi-hel-wg-103.conf "curl https://ifconfig.co/json"`
