### ISSUE TITLE
Comments in ovpn file not ignored

### ISSUE THREAD

**Issue by meldafert** [jamesmcm/vopono#212]
When using custom openvpn configuration files, vopono does not ignore commented out configuration (using either `#` or `;`).
Eg. given the file:
```ovpn
;proto tcp
proto udp
;remote my-old-server 1194
remote my-new-server 1196
```
vopono reports:
```
Found remotes: [Remote { host: Hostname("my-old-server"), port: 1194, protocol: TCP }, Remote { host: Hostname("my-new-server"), port: 1196, protocol: TCP }]
```
This can be worked around by removing the commented out lines from the configuration file.
However, especially when working with custom files provided by someone else, it would be better if commented out lines were ignored.

**Comment by jamesmcm** [comment]
Fixed in 0.10.6 release - https://github.com/jamesmcm/vopono/releases/tag/0.10.6 - thanks for the PR!
