### ISSUE TITLE
Unable to run GUI programs in namespace due to unavailable display

### ISSUE THREAD

**Issue by dpantel** [jamesmcm/vopono#215]
I am attempting to run a browser via vopono.  Both chromium and firefox fail with similar messages.

`$ vopono -v exec --custom ./config.ovpn --protocol openvpn chromium`

```
INFO  vopono::exec > Application chromium launched in network namespace vopono_c_sYuaqP5hQq2 with pid 54637
[54639:54639:0406/184144.553208:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[54639:54639:0406/184144.553224:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.

```

`$ vopono -v exec --custom ./config.ovpn --protocol openvpn firefox`

```
INFO  vopono::exec > Application firefox launched in network namespace vopono_c_sYuaqP5hQq2 with pid 55031
Error: cannot open display: :0
```

vopono 0.10.5
Mint 21.1 (Ubuntu 22.04)

**Comment by jamesmcm** [comment]
Are you using X11 normally?

**Comment by dpantel** [comment]
Yes

**Comment by dpantel** [comment]
Rebooted the system and vopono started just up; must have been a fluke
