### ISSUE TITLE
pactl language

### ISSUE THREAD

**Issue by Jayrgo** [jamesmcm/vopono#219]
`pactl info` cannot be parsed if the output is in another language.
I would prefer json output: `pactl -f json info` and get the value from `server_string`

https://github.com/jamesmcm/vopono/blob/a566ec58503251c6725e1d58d5f1549f6cc8faca/vopono_core/src/util/pulseaudio.rs#L7

**Comment by jamesmcm** [comment]
Fixed in 0.10.6 release - https://github.com/jamesmcm/vopono/releases/tag/0.10.6
