### ISSUE TITLE
Error when navigating to https://account.protonvpn.com/api/vpn/v2/users

### ISSUE THREAD

**Issue by 5p4r74cu5** [jamesmcm/vopono#229]
Hey all, I'm getting a error code when navigating to the URL for the Proton AUTH key. Any suggestions? I'm logged into Proton, not on a VPN and everything else on my internet connection is working fine.

Error message: `{"Code":404,"Error":"Path not found","Details":{}}`

EDIT: Sorry, didn't realise that's the expected behaviour.

**Comment by jamesmcm** [comment]
You should still be able to find it when checking the headers when you log in to the ProtonVPN web console, it doesn't need to be that page.

**Comment by jamesmcm** [comment]
Btw if this fails you can also check the requests it makes when loading the Downloads page (e.g. the request made to `/api/vpn` from there so all the headers and cookies are set).

Also note the specific `AUTH-xxx=yyy` cookie you need to copy is the one where `xxx` there matches the `x-pm-uid` header.

I've tried to make it a bit clearer in the User Guide - https://github.com/jamesmcm/vopono/blob/master/USERGUIDE.md#openvpn-sync-and-authentication

![protonvpn_header](https://github.com/jamesmcm/vopono/assets/54889/2fe78193-5675-480e-917d-f6ead17ea71e)


FWIW you can also use the Wireguard configs as custom providers e.g.:
```bash
$ vopono -v exec --custom ./hostname-RO-9.conf --protocol wireguard --provider custom --protonvpn-port-forwarding firefox
```
