### ISSUE TITLE
Error: invalid Zip archive: Could not find central directory end

### ISSUE THREAD

**Issue by adorableweasel** [jamesmcm/vopono#233]
I'm trying to get this setup for ProtonVPN and get to this step:

**_"Please log-in at https://account.protonvpn.com/dashboard and then visit https://account.protonvpn.com/api/vpn/v2/users and copy the value of the cookie starting with "AUTH-" in the request from your browser's network request inspector:"_**

Of which after following the steps, the result is this:

_**"Error: invalid Zip archive: Could not find central directory end"**_

Any advice?

Edit: Doing this on Ubuntu V 22.04.2 LTS

**Comment by lpapadakos** [comment]
Hello @adorableweasel  in my case this happened becaue the cookie I was pasting was malformed.

- Get the `Cookie:` line from the network request.
- Paste it in a text editor
- Now copy only the relevant cookie (there might be others in that line, like Session: e.t.c.
  (Keep only this part: AUTH-xyz...=abc... without the semicolon)
- Paste that into the vopono prompt

**Comment by jamesmcm** [comment]
Note the specific `AUTH-xxx=yyy` cookie you need to copy is the one where `xxx` there matches the `x-pm-uid` header.

I've tried to make it a bit clearer in the User Guide - https://github.com/jamesmcm/vopono/blob/master/USERGUIDE.md#openvpn-sync-and-authentication

![protonvpn_header](https://github.com/jamesmcm/vopono/assets/54889/2fe78193-5675-480e-917d-f6ead17ea71e)


FWIW you can also use the Wireguard configs as custom providers e.g.:
```bash
$ vopono -v exec --custom ./hostname-RO-9.conf --protocol wireguard --provider custom --protonvpn-port-forwarding firefox
```
