### ISSUE TITLE
specify mullvad server and run transmission-daemon

### ISSUE THREAD

**Issue by inkwell84** [jamesmcm/vopono#24]
Hello and thank you for your work on this. 

How can I specify US mullvad server?
How do I exec to put the transmission terminal service in the tunnel? (transmission-daemon).

Thank you again.

**Comment by jamesmcm** [comment]
Hi,

I'm not at my home computer right now but something like this should work:

```bash
$ vopono exec --provider mullvad --server us transmission-daemon
```

Or to use OpenVPN instead of Wireguard:

```bash
$ vopono exec --provider mullvad --protocol openvpn --server us transmission-daemon
```

The real question is whether the communication with the daemon will work if only the daemon is inside the network namespace. This is something worth testing, I'll check tomorrow if I get time.

**Comment by inkwell84** [comment]
Many thanks in advance, I have low expertise.

Any way to specify the us server, such as"us105"?

**Comment by inkwell84** [comment]
Following up: mullvad confirmed their Linux terminal app’s split-tunnel feature can only select those apps that do not use the VPN, rather than selecting those apps that only should use it, so it seems like VOPONO is our only potential solution! 👍

**Comment by jamesmcm** [comment]
Also regarding the specific server, it is possible on Wireguard but not on OpenVPN (just due to the way the config files are generated to match Mullvad's service, they used to be separate).

You can list the possible choices with:

```bash
$ vopono servers --protocol wireguard mullvad
$ vopono servers --protocol openvpn mullvad
```

**Comment by jamesmcm** [comment]
Hey, I finally had time to test the daemon.

It works but it's a little awkward as you can only connect to it from within the same network namespace, and you need to leave something else running to keep the namespace open (as the daemon technically stops running immediately).

```bash
# First launch firefox and keep it open
$ vopono -v exec --provider mullvad --server sweden firefox
# Then launch the daemon
$ vopono -v exec --provider mullvad --server sweden transmission-daemon
#  Now you can go to http://127.0.0.1:9091  and see the web interface in that Firefox session (it will not work outside the namespace)
```

I'll think about how I can fix forcing it to stay open when running a daemon (or otherwise detecting that the daemon is still running). It might also be possible to allow some port forwarding (i.e. for the daemon) outside of the namespace so you could access the web interface from any browser not in the namespace, but it gets a bit complicated due to also running the killswitch rules.

**Comment by inkwell84** [comment]
Thanks for looking into this, unfortunately transmission is on a headless Ubuntu home server. No GUI for firefox... I’m just operating transmission from a windows laptop on home network

-------
Colby Roof
wcroof@gmail.com

**Comment by jamesmcm** [comment]
I mean you can run anything that won't terminate first, i.e. `vi`, etc.

**Comment by jamesmcm** [comment]
Cool, I looked in to this more and got it to work locally.

There are two parts:

- Allowing connections in to the network namespace for specific ports
- Forwarding the port on the host machine to the port on the network namespace, for specific ports

The first can be done with:

```bash
sudo ip netns exec vopono_azire_norway iptables -I OUTPUT -p tcp --sport 9091 -j ACCEPT
```

Where in this case `vopono_azire_norway` is the namespace name and the port is 9091. This will be simple to add as an option to vopono.

The second can be achieved with socat, i.e.:

```bash
socat tcp-listen:9091,reuseaddr,fork tcp-connect:10.200.1.2:9091
```

The idea will be to implement this port proxying functionality in Rust directly and add it as an optional feature (so in your case you could have other devices connect to the transmission-daemon as normal). I couldn't get this to work with iptables/nftables rules on the host alone, and also I don't think it's a great idea to edit the host machine's rules so much, so I think the built-in proxy is the way to go.

Note for transmission-daemon there is one extra point to be aware of - you have to whitelist external IPs which can access the webserver:

> Either disable the IP address whitelist or add your address to it.
> If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.

The awkward thing here is that the whitelisted IP address would need to be the host's side of the veth pair - but that isn't known until vopono runs and allocates them. So I'll have vopono return both IP addresses of the host from the namespace point of view and vice versa for cases like this, but overall I think the best option would be to disable the whitelist in transmission-daemon in this case.

------------------------------------

I'll try to create a PR covering this tomorrow, so I can make a new release this weekend.

**Comment by inkwell84** [comment]
AWESOME! Thank you!

-------
Colby Roof
wcroof@gmail.com

**Comment by jamesmcm** [comment]
This should now be possible with vopono 0.5.0: https://github.com/jamesmcm/vopono/releases/tag/0.5.0

i.e. run `transmission-daemon` in vopono with the keep-alive option and forwarding port 9091 (change this if you run the webserver on a different port)

```bash
$ vopono -v exec -k -f 9091 --provider mullvad --server usa "transmission-daemon -a *.*.*.*"
```

Then the web server should be available at http://127.0.0.1:9091 as long as vopono and the transmission-daemon are running.

Note the `-a *.*.*.*` is required to disable the IP whitelist for accessing the server.

**Comment by inkwell84** [comment]
Thank you. I’m still not having success getting the syntax correct for a specific USA server. Say I want server us52...

-------
Colby Roof
wcroof@gmail.com

**Comment by jamesmcm** [comment]
For use with Wireguard, you can specify `usa-us52` as the server:

```bash
$ vopono -v exec -k -f 9091 --provider mullvad --server usa-us52 "transmission-daemon -a *.*.*.*"
```

The server argument is actually a prefix, and you can see all possibilities for a given prefix and provider with:
```bash
$ vopono servers mullvad --prefix usa
provider        protocol        config_file
Mullvad openvpn usa-us.ovpn
Mullvad wireguard       usa-us40.conf
Mullvad wireguard       usa-us145.conf
Mullvad wireguard       usa-us52.conf
...
```

Note that for OpenVPN the servers per country are combined in one config file (as is the case when Mullvad generates the config files). You could just copy that config file and remove the servers you don't want.

I.e. create `~/.config/vopono/mv/openvpn/usa-miami.ovpn`:

```
client
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
remote-cert-tls server
ping 10
ping-restart 60
sndbuf 524288
rcvbuf 524288
cipher AES-256-CBC
tls-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA
auth-user-pass mullvad_userpass.txt
ca mullvad_ca.crt
tun-ipv6
script-security 2
proto tcp
remote 37.120.215.130 443 # us-mia-002
```
 To use us-mia-002 only for example, and then use:

```bash
$ vopono -v exec -k -f 9091 --provider mullvad --protocol openvpn --server usa-miami "transmission-daemon -a *.*.*.*"
```

To run it, just like a normal OpenVPN config.
