### ISSUE TITLE
interface config option no longer recognized

### ISSUE THREAD

**Issue by Ghosthree3** [jamesmcm/vopono#254]
Prior to the current release (0.10.9) using the line `interface = "br0"` in my config.toml worked as expected, now vopono complains `Multiple network interfaces are active` and defaults to, unfortunately, the incorrect device.

Passing `-i br0` works, and all other config options seem to be being read correctly as well.

**Comment by jamesmcm** [comment]
Thanks, it must be an issue with it de-serialising the string now that all config arguments are handled the same way, I'll take a look.

**Comment by jamesmcm** [comment]
@Ghosthree3 this is fixed on master now btw.

**Comment by Ghosthree3** [comment]
Confirmed.
