### ISSUE TITLE
Running without sudo for an unsecure systemd service

### ISSUE THREAD

**Issue by brauliobo** [jamesmcm/vopono#279]
Hi, I want to run https://github.com/brauliobo/media-downloader-bot which relies on `DynamicUser=true` for security reasons with vopono.

It seems it requires sudo to run, so it erroring:
```
ago 05 14:13:32 bhavapower vopono[872919]:  2024-08-05T17:13:32.980Z INFO  vopono_core::util > Calling sudo for elevated privileges, current user will be used as default user
ago 05 14:13:32 bhavapower vopono[872927]: sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
ago 05 14:13:32 bhavapower vopono[872927]: sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
```

Tried to add caps but it didn't help:
```
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_ADMIN
```

Is there a way to not run without sudo by manually hooking the necessary caps?

**Comment by brauliobo** [comment]
An alternative would be to only allow certain commands to be run with sudo, given they are specified by vopono, so the use of sudo remains restricted and secure

**Comment by brauliobo** [comment]
Found a solution that sets up a service that creates a network namespace and then uses it with `NetworkNamespacePath=` in another service. Code at https://gist.github.com/brauliobo/94ac38fe2695f405df2cbd8d0a1da207

**Comment by jamesmcm** [comment]
Btw you could use:

```bash
vopono exec --create-netns-only ...
```

To do just the network namespace part if you want to use it there.
