### ISSUE TITLE
[Feature Request] Option for disabling output ("quiet mode") 

### ISSUE THREAD

**Issue by xenorio** [jamesmcm/vopono#280]
I'm using vopono to limit my VPN connections to a specific shell, simply by executing zsh directly via vopono.

It would be great if it was possible to make vopono quiet (like a --quiet/-q commandline argument) so it does not spit out any logs except when there's an error. In my personal usecase, purely for style reasons. I'm already modifying the PS1 variable (shell prompt) to indicate whether the shell is connected to a VPN, no need for all the extra information cluttering up the terminal.

**Comment by jamesmcm** [comment]
This should be possible by setting the `RUST_LOG` environment variable, it's just right now it seems it isn't being passed forward correctly, I'll try to fix it soon.

**Comment by jamesmcm** [comment]
`--silent` is added in release v0.10.11 - and `RUST_LOG` also works as expected when `-v` is not specified for just the logging output (not application output).
