### ISSUE TITLE
Wireguard - use random server?

### ISSUE THREAD

**Issue by necrevistonnezr** [jamesmcm/vopono#281]
Is it possible to just let vopono choose/ use a random server?
I‘m using PIA with vopono and sometimes I just want to use a random region / server (e.g. to overcome download quotas).

**Comment by jamesmcm** [comment]
It uses the server name as a prefix for choosing the config file, so passing an empty string works:


```bash
$ vopono exec --provider protonvpn --protocol openvpn --server "" firefox-developer-edition
 2024-10-13T08:53:43.108Z INFO  vopono_core::util           > Chosen config: /home/archie/.config/vopono/proton/openvpn/united_states-us.ovpn

 $ vopono exec --provider protonvpn --protocol openvpn --server "" firefox-developer-edition
 2024-10-13T08:54:05.366Z INFO  vopono_core::util           > Chosen config: /home/archie/.config/vopono/proton/openvpn/thailand-th.ovpn
```

**Comment by necrevistonnezr** [comment]
Fantastic, thanks! Works with wireguard servers as well

**Comment by Friend524** [comment]
> It uses the server name as a prefix for choosing the config file, so passing an empty string works:
> 
> ```shell
> $ vopono exec --provider protonvpn --protocol openvpn --server "" firefox-developer-edition
>  2024-10-13T08:53:43.108Z INFO  vopono_core::util           > Chosen config: /home/archie/.config/vopono/proton/openvpn/united_states-us.ovpn
> 
>  $ vopono exec --provider protonvpn --protocol openvpn --server "" firefox-developer-edition
>  2024-10-13T08:54:05.366Z INFO  vopono_core::util           > Chosen config: /home/archie/.config/vopono/proton/openvpn/thailand-th.ovpn
> ```

Am I correctly understanding that for Wireguard on ProtonVPN, this randomization technique won't currently work? In the User Guide under the ProtonVPN>Wireguard section, it says to list a custom server. I downloaded a few I want to use.

To be clear this is not an issue for me, I'm just curious.

**Comment by jamesmcm** [comment]
Yeah, it doesn't apply to custom config files atm. It would be a simple change to make it work the same way, but it's probably more confusing than beneficial - e.g. if you make a typo etc.
