### ISSUE TITLE
Userguide implies IVPN still offer port forwarding

### ISSUE THREAD

**Issue by hughobrien** [jamesmcm/vopono#285]
https://github.com/jamesmcm/vopono/blob/62b6026be02a2fe9db421bfe2874376bd51fa1af/USERGUIDE.md?plain=1#L666

They have unfortunately [removed it](https://www.ivpn.net/blog/gradual-removal-of-port-forwarding)

**Comment by jamesmcm** [comment]
Damn, just like Mullvad.

Thanks, I'll fix it when I get some time.

**Comment by jamesmcm** [comment]
Fixed in release v0.10.11 - thanks for noticing it!
