### ISSUE TITLE
protovpn AUTH cookie not retrievable

### ISSUE THREAD

**Issue by Saph123** [jamesmcm/vopono#286]
Doing the procedure : login-in to dashboard of protovpn
Then I go to account on a new tab, but in cookies, there is only a Session-Id cookie and not a AUTH-xxx cookie...
Did they change the website?

**Comment by Saph123** [comment]
my bad, I'm stupid

**Comment by jamesmcm** [comment]
No problem, depending on which request you look at it will probably in the request headers:

![2024-11-19-185225_932x1563_scrot](https://github.com/user-attachments/assets/3c7fea54-a2df-4f3b-a60a-ca52c3273f25)
