### ISSUE TITLE
run0 support

### ISSUE THREAD

**Issue by Friend524** [jamesmcm/vopono#287]
This is my first time submitting a request, so please bear with me :)

**Description**

When running vopono commands, by default, it will call sudo as needed. However, the only way to seemingly get this to work for run0 is to run the entire command as elevated, which is less than ideal for reasons stated in the User Guide.

**Steps to reproduce the issue**

Run any command that requires elevated privileges.

**Expected behavior**

For this to work as well as it does for systems with sudo.

**Actual behavior**

It errors out when requesting sudo.

**Any error messages or logs**

DEBUG vopono_core::util > Using config dir from $HOME config: /var/home/user/.config
DEBUG vopono_core::util::pulseaudio > Setting PULSE_SERVER to /run/user/1000/pulse/native
INFO  vopono_core::util             > Calling sudo for elevated privileges, current user will be used as default user
DEBUG vopono_core::util             > Args: ["/var/home/user/.cargo/bin/vopono", "-v", "exec", "--provider", "custom", "--custom", "/var/home/user/wg-LOCATION-1.conf", "--protocol", "wireguard", "--custom-port-forwarding", "vpn"]
Error: Executing sudo -E ["/var/home/user/.cargo/bin/vopono", "-v", "exec", "--provider", "custom", "--custom", "/var/home/user/VPN WG files/wg-LOCATION-1.conf", "--protocol", "wireguard", "--custom-port-forwarding", "vpn"]

**Environment:** Gnome
**Operating System:** Silverblue
**Version:** 41.20241208.0

**Comment by Friend524** [comment]
Upon review, I think I misunderstood a number of things. 

https://github.com/jamesmcm/vopono/issues/189

This issue about this, but I didn't realize it was relevant at the time. And it looks like this was incorporated to address these kinds of issues: https://github.com/jamesmcm/vopono/blob/master/USERGUIDE.md#creating-only-network-namespace

I am going to test if this also works with flatpaks, which I think it should. Will mark as closed for now.

**Comment by Friend524** [comment]
Nevermind, couldn't get past the first command to create the network namespace, it seems that it calls sudo again :( I'll leave this open now to prevent confusion and hopefully get some feedback. After re-reading #189 again, maybe I need to create a script for now?

**Comment by jamesmcm** [comment]
I haven't used run0 yet, one issue here is atm we use https://crates.io/crates/sudo to determine when to relaunch with sudo. So that would also need to work with run0.

**Comment by Friend524** [comment]
@jamesmcm 

I understand, no worries! I forgot that I simply had to run the network namespace command as run0 :)
------------

However, I ran into an another issue while doing so:

Error: natpmpc failed - likely that this server does not support port forwarding, please choose another server

I am unclear why this happened. It might be my setup.

I tested this with multiple Proton conf files with P2P enabled - Secure Core both enabled and disabled.

I don't have user namespaces enabled, although my understanding was that network namespaces was not reliant upon that. Or perhaps, does Vopono handle things through user namespaces?

No worries if so, since I could just enable user namespaces if need be - just wondering how it works. I did not know if there was a mechanism to gain more informative logs beyond "natpmpc failed".
