### ISSUE TITLE
Automatically detect whether Wireguard or OpenVPN when using custom config

### ISSUE THREAD

**Issue by jamesmcm** [jamesmcm/vopono#32]
Make `--protocol` optional when using a custom VPN config file by automatically detecting whether the config file passed in is for Wireguard (wg-quick) or OpenVPN (an ovpn config file).

**Comment by dlemel8** [comment]
Hey @jamesmcm , I want to do this.
Can you guide me a bit?
Thanks.

**Comment by jamesmcm** [comment]
Hi,

Thanks, so the relevant part is:

https://github.com/jamesmcm/vopono/blob/7c52e10890ff4c9a51024dd9b82cc79ce9df9ccd/src/main.rs#L92-L96

and

https://github.com/jamesmcm/vopono/blob/7c52e10890ff4c9a51024dd9b82cc79ce9df9ccd/src/main.rs#L119-L122

At the moment when using a custom provider (with a custom config file) the protocol must be given (since we cannot infer a default from the provider - unlike, for example, ProtonVPN where only OpenVPN is available).

The idea would be to write a utility function that given a `PathBuf` to the config file, can read the file and tell us if it is an OpenVPN config file or a Wireguard wg-quick config file. This should be simple since the latter is pseudo-TOML so you could just try to detect the `[Interface]` section existing for example.

The function signature could be:

```rust
fn get_config_file_protocol(config_path: &PathBuf) -> Protocol {
   // read file to String
   if file.contains(&"[Interface]"){
     Protocol::Wireguard
     } else {
     Protocol::OpenVpn
    }
}
```

Where `Protocol` is an enum defined in `vpn.rs`:

https://github.com/jamesmcm/vopono/blob/7c52e10890ff4c9a51024dd9b82cc79ce9df9ccd/src/vpn.rs#L64-L70

Then with that function you can remove the `bail!` call above, and instead modify the assignment to `protocol` such that it calls calls the `get_config_file_protocol()` method if the protocol argument is not provided and a custom config file is provided - i.e. use `.unwrap_or_else()`: https://doc.rust-lang.org/beta/std/option/enum.Option.html#method.unwrap_or_else

That will require a bit of re-arrangement to ensure it is only used in the custom config case.

Let me know if you have any questions or issues, I'm happy to help.

**Comment by dlemel8** [comment]
@jamesmcm great, thanks!
I will start working on it soon :)
