### ISSUE TITLE
Getting "Could not parse pactl output!" when using exec command

### ISSUE THREAD

**Issue by dandersch** [jamesmcm/vopono#50]
Verbose output looks like this:
```
./vopono -v exec --provider ProtonVPN --server us bash
 2020-11-30T18:08:03.306Z DEBUG vopono::pulseaudio > Setting PULSE_SERVER to /run/user/1000/pulse/native
 2020-11-30T18:08:03.306Z INFO  vopono::util       > Calling sudo for elevated privileges, current user will be used as default user
 2020-11-30T18:08:03.306Z DEBUG vopono::util       > Args: ["./vopono", "-v", "exec","--provider", "ProtonVPN", "--server", "us", "bash"]
Error: Could not parse pactl output!
```
Running `pactl info` as root fails for me, which seems to cause the error. I think this has to with running pulseaudio system-wide vs. per-user. As a workaround I added `if std::env::var("PULSE_SERVER").is_err() { ...` before `get_pulse_server()` gets called and now everything seems to work.

**Comment by jamesmcm** [comment]
Thanks! Please make a PR if you can, or I'll try to test it and do it on Wednesday 🙂 

As mainly it'd be good to still be able to share to pulseaudio even if it isn't running as root.

**Comment by jamesmcm** [comment]
Hmm checking this, it usually doesn't run as root.

What output do you get from `pactl info` (as your normal user) ?

**Comment by jamesmcm** [comment]
I've also released a new version making it only  a warning in the case the parsing fails: https://github.com/jamesmcm/vopono/releases/tag/0.6.1

It'd be great to have the `pactl info` output for comparison though.

**Comment by dandersch** [comment]
The new version works well for me, thanks.

Here is the output of `pactl info`:
```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 34
Server Protocol Version: 34
Is Local: yes
Client Index: 43
Tile Size: 65472
User Name: da
Host Name: arch
Server Name: pulseaudio
Server Version: 14.0
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1b.0.analog-stereo
Default Source: alsa_input.pci-0000_00_1b.0.analog-stereo
Cookie: 1e75:c48d
```

and the error for `sudo pactl info`:
```
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

As you can see in the first post it manages to set `PULSE_SERVER` for the first time and only fails after saying `Calling sudo for elevated privileges`. That's why I thought it might be related to my output for `pactl info` as root.

**Comment by jamesmcm** [comment]
Oh thanks, now I see the issue, it's that it tries to set it twice. I guess I never hit this issue myself since it works as root for me too.

It's okay for now, but to avoid the warning I'll move it later in the `exec` code path at some point.

Thanks for reporting it!
