### ISSUE TITLE
Generated Wireguard config files for Mullvad that contain private keys are world readable

### ISSUE THREAD

**Issue by joelpet** [jamesmcm/vopono#56]
Steps to reproduce:

1. `vopono sync --protocol Wireguard Mullvad`
2. Enter a valid 'Mullvad account number'
3. Choose to 'Generate a new key pair'
4. 'Enter port number' 51820

Expected:

* All lines that `ls -l ~/.config/vopono/mv/wireguard/` output start with `-rw-------`.

Actual:

* All lines that `ls -l ~/.config/vopono/mv/wireguard/` output start with `-rw-r--r--`.

**Comment by jamesmcm** [comment]
Thanks for reporting this, I think it comes from the permissions setting (to avoid the config dir being written as root), see: https://github.com/jamesmcm/vopono/blob/b87d4724117d0ecc64a098e7bae5a2da8b11bb05/src/util/mod.rs#L83-L94

Hopefully just adding a `chmod` there should address this, eventually it should be refactored a bit to ensure we never write user config files when running as root.

**Comment by joelpet** [comment]
>  I think it comes from the permissions setting (to avoid the config dir being written as root)

My Rust skills are a little... rusty. :) But that looks like it's only changing the *owner* of the files, and not their *mode*. I was rather under the impression that `let mut f = std::fs::File::create(path);` simply creates each config file according to the current umask, which is by default 022, resulting in files written with mode 644. If this is indeed the case, then one would probably use https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html#tymethod.set_mode to fix it.

> Hopefully just adding a `chmod` there should address this, eventually it should be refactored a bit to ensure we never write user config files when running as root.

This sounds very wise.

**Comment by jamesmcm** [comment]
Thanks, I think we can make the mode change with no issues elsewhere, as it's not like we need anything world-readable.

**Comment by jamesmcm** [comment]
Fixed in release 0.6.4 - https://github.com/jamesmcm/vopono/releases/tag/0.6.4
