### ISSUE TITLE
running go binary

### ISSUE THREAD

**Issue by mstaack** [jamesmcm/vopono#70]
amazing tool this is !

sometimes i get this error during start, but most of the times it just works:
```
thread '<unnamed>' panicked at 'Failed to bind: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/basic_tcp_proxy-0.3.0/src/lib.rs:36:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jamesmcm** [comment]
Are you forwarding any ports from the namespace - i.e. with the `-f` flag?

If so, are these ports free on the host machine?

**Comment by mstaack** [comment]
yes i do, but the one i specified on my first vopono call.
then i ctrl-c the thing and its seems as the port is not freed correctly after that?!

**Comment by jamesmcm** [comment]
Hmm I can't replicate this locally, can you paste the exact commands you run please?

**Comment by mstaack** [comment]
Have not been able to reproduce this lately. Thanks for your time and awesome tool ;)
