### ISSUE TITLE
How to run this as a systemd service.

### ISSUE THREAD

**Issue by blackCauldron7** [jamesmcm/vopono#78]
I want to run transmission-daemon under a vpn connection as a systemd service but the process fails because `Could not parse PULSE_SERVER from pactl info output: Err(Could not parse pactl output!:
)`
Thanks for the amazing tool. :)

**Comment by jamesmcm** [comment]
How did you solve this btw? I think the best way would be to set the SUID bit on the binary and then create a unit file. 

It'd be cool to add the unit file to the repo though.

**Comment by blackCauldron7** [comment]
opened #79 because this not related to systemd. It doesn't work on runit too.
