### ISSUE TITLE
running flatpak apps using vopono

### ISSUE THREAD

**Issue by daliolores** [jamesmcm/vopono#96]
Hi! Is there a way to run flatpak apps using vopono? I tried it with the flatpak run command but had no luck.
Thanks in advance,

**Comment by jamesmcm** [comment]
I tried this out, do you hit the issue that it detects the sudo access?

> error: "flatpak run" is not intended to be run as `sudo flatpak run`, use `sudo -i` or `su -l` instead and invoke "flatpak run" from inside the new shell

The weird thing is that it does it even for please, etc. - it'll be pretty painful to work around if we need to switch users prior to launching the application.

**Comment by jamesmcm** [comment]
Here's a work-around (works for me):

```
vopono -v exec --protocol Wireguard --provider Mullvad --server uk  "SUDO_COMMAND='' flatpak run org.mozilla.firefox"
```

**Comment by daliolores** [comment]
Thank you for your answer! I am able to start some flatpak container using your workaround on my debian system. But for example I am not able to run gnome.Boxes and upgrade Fedora using the dnf command. I just may run Fedora but without having an internet connection. When trying to run Pithos it is telling about some temporary name resolving error. Is there some configuration I need to change?

**Comment by jamesmcm** [comment]
Closing since all Flatpaks I've tested work okay (even on the Steam deck). The above cases might be due to some apps (like Gnome ones) using a daemon on the host for actual connections and/or not running a separate process when executed.

**Comment by daliolores** [comment]
Thanks again for your answer! And your work! I've tested it again and was able to update Windows 10 and the latest Ubuntu running Gnome-Boxes in Vopono. While this I was listening to some tracks running Pithos. It would be cool to have Vopono in the Debian repositories. Best regards,
