### ISSUE TITLE
Question: Is Arch ARM Raspberry Pi supported for ARM v6

### ISSUE THREAD

**Issue by exup** [jamesmcm/vopono#98]
Hi, I am trying to install the vopono, vopono-git and vopono-bin from Arch AUR. On a RPI 1 but not sure if its supported. 
As the RPi1 is ARM V6 I dont think it can run 64 bit instructions? I am a little hazy around the arch ARM architecture. From what I gather.

RPi 1 = ARM v6 ARM 32?
RPi 2 = ARM v7 ARM 32 bit?
RPi 3 and 4 = ARM v8 which has an AArch64 install available

If I try to install vopono-bin on RPi 1 (with the A flag)  I get 

> makepkg -Asi
==> Making package: vopono-bin 0.8.2-1 (Sun 18 Jul 2021 09:37:49)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> Extracting sources...
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'vopono': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...

Compiling git or git-git takes over 48hours and fails alot so gave up.

This is my OS "5.10.48-1-ARCH #1 SMP Fri Jul 9 23:11:22 UTC 2021 armv6l GNU/Linux"

**Comment by jamesmcm** [comment]
The RPi 1 uses ARMv6 with hard float so the right target is:

```
arm-unknown-linux-gnueabihf | ARMv6 Linux, hardfloat (kernel 3.2, glibc 2.17)
```

You can cross-compile for that on a faster machine and then copy the binary over.

See https://rust-lang.github.io/rustup/cross-compilation.html for details using rustup.

Note the bigger issue might be Wireguard and nftables support on older kernel versions, so I'd recommend using OpenVPN and the iptables firewall option.

**Comment by exup** [comment]
OK interesting I have never cross compiled, but will give it a go.  Looking at your link though I am a bit clueless on what to do.

On my Arch 64 bit laptop git clone https://aur.archlinux.org/vopono-bin.git (Eg into my downloads folder)
Then `rustup target add arm-unknown-linux-gnueabihf` which install the armv6 tool chain components
Then `rustup target add --toolchain arm-unknown-linux-gnueabihf <target>`

should it be ~/downloads/vopono-bin/pkg/vopono.bin ?

**Comment by jamesmcm** [comment]
It'd be like:

```
rustup target add arm-unknown-linux-gnueabihf
paru -S arm-linux-gnueabihf-gcc
cargo build --target arm-unknown-linux-gnueabihf --release
```

Note you need `arm-linux-gnueabihf-gcc` - I can't get it to build on my system as `arm-linux-gnueabihf-glibc-2.33-3` fails to build.

**Comment by exup** [comment]
I might close this as strictly not issue with the app. My skill set is not able to cross compile so now I am just using a RPi4 on AARCH64 image. Everything is working well and stable, app has been running non stop now for 3 days, no drop outs.

**Comment by jamesmcm** [comment]
Yeah, it's tricky I'm not sure why the compiler fails to install.

It might be possible [with this Docker image](https://github.com/dlecan/rust-crosscompiler-arm) - I'll try it out when I get sometime (it'll be useful to be familiar with in any case!).

That's good to know it works on the RPi4 okay though.
