### ISSUE TITLE
ProtonVPN unable to connect

### ISSUE THREAD

**Issue by exup** [jamesmcm/vopono#99]
Hi, I have run "vopono sync" and followed the prompts for proton VPN
Then run 
vopono exec --provider protonVPN --server netherlands --no-killswitch transmission-daemon

but then get this error

` 2021-07-19T05:02:49.414Z INFO  vopono::util > Calling sudo for elevated privileges, current user will be used as default user
 2021-07-19T05:02:49.579Z INFO  vopono::util > Chosen config: /home/user1/.config/vopono/proton/openvpn/netherlands-nl-free.ovpn
 2021-07-19T05:02:49.585Z INFO  vopono::netns > Created new network namespace: vopono_proton_netherlands
 2021-07-19T05:02:49.695Z INFO  vopono::netns > IP address of namespace as seen from host: 10.200.1.2
 2021-07-19T05:02:49.695Z INFO  vopono::netns > IP address of host as seen from namespace: 10.200.1.1
 2021-07-19T05:02:49.903Z INFO  vopono::openvpn > Launching OpenVPN...
 2021-07-19T05:02:52.972Z INFO  vopono::exec    > Application transmission-daemon launched in network namespace vopono_proton_netherlands with pid 1390
Bind /etc/netns/vopono_proton_netherlands/openvpn.log -> /etc/openvpn.log failed: No such file or directory
 2021-07-19T05:02:53.017Z INFO  vopono::netns   > Shutting down vopono namespace - as there are no processes left running inside
`

Note my .config/vopono/config.toml file is empty?
I also ran "sudo firewall-cmd --state" but command not found?
This is on RPi4 running aarch64
I have installed openvpn but never configured it.

I ran it on my Arch Plasma laptop and works fine. All be it using chromium as a test.

**Comment by exup** [comment]
Whoops user error, I did not read the manual where is clearly points out this is a particular note around transmission-daemon.
So after using this instead a test download confirms my IP is in Netherlands

`vopono -v exec -k -f 9091 --provider protonvpn --server netherlands "transmission-daemon -a *.*.*.*"`

[https://github.com/jamesmcm/vopono/blob/master/USERGUIDE.md#daemons-and-servers](url)

**Comment by jamesmcm** [comment]
Yeah, due to the way it forks vopono doesn't realise the process hasn't just ended and so kills the namespace by default.

There should be a better way of dealing with this since the new daemon process inherits the network namespace (so it should be detectable somehow), but for some reason the parent process ID is not the same as the original one.

**Comment by exup** [comment]
May I ask if I need to worry about the listing of these multiple lines whenever I start vopono, it does connect eventually.

`DEBUG vopono::netns             > ip netns exec vopono_custom_Neth ip6tables -A OUTPUT -o tun+ -j ACCEPT
Bind /etc/netns/vopono_custom_Neth/openvpn.log -> /etc/openvpn.log failed: No such file or directory
`

**Comment by jamesmcm** [comment]
It's okay, it still reads the OpenVPN log file correctly.

**Comment by exup** [comment]
Awesome work, I have been sharing your project with as many people as I can, including late Night Linux group. I hope this project gets wider attention it deserves. Googling for a solution for this type of problem or scenario was very hard, first the way you phrase it secondly some solutions where mind boggling confusing. Do you have a tip jar?

**Comment by jamesmcm** [comment]
Thanks! I don't have tipping here as it always seems more effort than it's worth with the taxes, etc. but the best way to contribute would be via more VPN providers (as I cannot use / add all of them).

Speaking of interesting Linux projects, you might also be interested in the [ALMA](https://github.com/r-darwish/alma) tool for Arch Linux persistent + portable USB installations. [I wrote about it here](http://jamesmcm.github.io/blog/2020/09/09/alma/#en) where I created my [preset files](https://github.com/jamesmcm/arch-i3-usb).
